### ISSUE TITLE
java.lang.IllegalStateException in setAdvertisingID

### ISSUE THREAD

**Issue by n-belokopytov** [snowplow/snowplow-android-tracker#105]
I am initializing analytics tracker in the onCreate method of my app and I am getting this:

     Caused by: java.lang.IllegalStateException: Calling this from your main thread can lead to deadlock
            at com.google.android.gms.common.internal.zzx.zzbe(Unknown Source)
            at com.google.android.gms.ads.identifier.AdvertisingIdClient.finish(Unknown Source)
            at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(Unknown Source)
            at com.snowplowanalytics.snowplow.tracker.Subject.setAdvertisingID(Subject.java:189)
            at com.snowplowanalytics.snowplow.tracker.Subject.setContextualParams(Subject.java:89)
            at com.snowplowanalytics.snowplow.tracker.Subject.<init>(Subject.java:80)
            at com.chefsfeed.Analytics.getSnowplowInstance(Analytics.java:276)

Here is the code in getSnowplowInstance method:

            RequestCallback callback = new RequestCallback() {
                @Override
                public void onSuccess(int successCount) {
                    Log.d(TAG, "Buffer length for POST/GET:" + successCount);
                }
                @Override
                public void onFailure(int successCount, int failureCount) {
                    Log.d(TAG, "Failures: " + failureCount + "; Successes: " + successCount);
                }
            };

            Emitter e2 = new Emitter
                    .EmitterBuilder("com.chefsfeed", context)
                    .callback(callback)
                    .build();

            // Create a Tracker with all options
            mTracker = new Tracker
                    .TrackerBuilder(e2, context.getPackageName(), context.getApplicationInfo().name)
                    .base64(true) // Optional - defines if we use base64 encoding
                    .platform(DevicePlatforms.Mobile) // Optional - defines what platform the event will report to be on
                    .subject(new Subject(context)) // Optional - a subject which contains values appended to every event
                    .build();

Also unrelated to that - your lib sure has a lot of dependencies and is a pain to integrate. Adding 
-dontwarn com.snowplowanalytics.snowplow.tracker.**
-dontwarn com.fasterxml.jackson.databind.**
-dontwarn okio.**
-dontwarn rx.internal.util.unsafe.**
to the proguard and all the corresponding dependencies to the gradle file.

**Comment by jbeemster** [comment]
Need to add IllegalStateException to this try/catch block: https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-android-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/Subject.java#L187-L196
