### ISSUE TITLE
NPE when subject is null

### ISSUE THREAD

**Issue by n-belokopytov** [snowplow/snowplow-android-tracker#107]
Crash

     Caused by: java.lang.NullPointerException
            at com.snowplowanalytics.snowplow.tracker.Tracker.addDefaultContextData(Tracker.java:180)
            at com.snowplowanalytics.snowplow.tracker.Tracker.completePayload(Tracker.java:149)
            at com.snowplowanalytics.snowplow.tracker.Tracker.trackUnstructuredEvent(Tracker.java:371)
            at com.snowplowanalytics.snowplow.tracker.Tracker.trackScreenView(Tracker.java:585)
            at com.snowplowanalytics.snowplow.tracker.Tracker.trackScreenView(Tracker.java:547)
            at com.chefsfeed.Analytics.activityStart(Analytics.java:191)

This is the code of tracker creation

            RequestCallback callback = new RequestCallback() {
                @Override
                public void onSuccess(int successCount) {
                    Log.d(TAG, "Buffer length for POST/GET:" + successCount);
                }
                @Override
                public void onFailure(int successCount, int failureCount) {
                    Log.d(TAG, "Failures: " + failureCount + "; Successes: " + successCount);
                }
            };

            Emitter e2 = new Emitter
                    .EmitterBuilder("com.chefsfeed", context)
                    .callback(callback)
                    .build();

            // Create a Tracker with all options
            mTracker = new Tracker
                    .TrackerBuilder(e2, context.getPackageName(), context.getApplicationInfo().name)
                    .base64(true) // Optional - defines if we use base64 encoding
                    .platform(DevicePlatforms.Mobile) // Optional - defines what platform the event will report to be on
                    .build();

Notice the absence of an optional subject setter.

NPE is raised during trackScreenView in
            String idScreen = cfActivity.getClass().getCanonicalName();
            tracker.trackScreenView(cfActivity.getActivityName(), idScreen);

**Comment by jbeemster** [comment]
Thanks for raising @n-belokopytov.  Need to wrap a check for `Subject == Null` around this block: https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-android-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/Tracker.java#L180-L189
