### ISSUE TITLE
Crash RxJava 

### ISSUE THREAD

**Issue by lixiaoyi** [snowplow/snowplow-android-tracker#131]
In the production app, we have many crashes on the RxJava:

java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:52)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: rx.exceptions.OnErrorNotImplementedException
	at rx.Observable$31.onError(Observable.java:7134)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:154)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.innerError(OperatorMerge.java:429)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.access$800(OperatorMerge.java:93)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onError(OperatorMerge.java:552)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:147)
	at rx.internal.operators.OperatorOnBackpressureBuffer.pollQueue(OperatorOnBackpressureBuffer.java:159)
	at rx.internal.operators.OperatorOnBackpressureBuffer.access$000(OperatorOnBackpressureBuffer.java:29)
	at rx.internal.operators.OperatorOnBackpressureBuffer$2.onError(OperatorOnBackpressureBuffer.java:94)
	at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:49)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:58)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:41)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:30)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable.unsafeSubscribe(Observable.java:7304)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.handleNewSource(OperatorMerge.java:188)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:158)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:93)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
	at rx.internal.operators.OperatorUnsubscribeOn$1.onNext(OperatorUnsubscribeOn.java:52)
	at rx.internal.operators.OperatorSubscribeOn$1$1$1.onNext(OperatorSubscribeOn.java:76)
	at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:231)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:84)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
	at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:51)
	at rx.Scheduler$Worker$1.call(Scheduler.java:120)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
	... 7 more
Caused by: java.lang.NullPointerException
	at android.net.Uri$Builder.appendQueryParameter(Uri.java:1493)
	at com.snowplowanalytics.snowplow.tracker.Emitter.requestBuilderGet(Emitter.java:406)
	at com.snowplowanalytics.snowplow.tracker.Emitter.performEmit(Emitter.java:316)
	at com.snowplowanalytics.snowplow.tracker.Emitter.access$lambda$6(Emitter.java)
	at com.snowplowanalytics.snowplow.tracker.Emitter$$Lambda$7.call(Unknown Source)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
	... 26 more
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.snowplowanalytics.snowplow.tracker.utils.storage.EmittableEvents.class
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:58)
	... 26 more

**Comment by alexanderdean** [comment]
Assigning to Josh...

**Comment by jbeemster** [comment]
Hi @lixiaoyi could you please copy and paste your tracker and emitter object creation here so I can see what could be causing it?

**Comment by lixiaoyi** [comment]
This crash happen on 0.3.0:
     /*snowplow*/
    compile 'com.snowplowanalytics:snowplow-android-tracker:0.3.0'
    compile 'com.snowplowanalytics:snowplow-java-tracker-core:0.2.0'
    compile 'io.reactivex:rxandroid:0.24.0'

I don't know if it still the crash on the 0.4.0. 
But for now, I will try to use the classic lib on the next release instead of RxJava, until you find something to fix:
compile 'com.snowplowanalytics:snowplow-android-tracker-classic:0.4.0'

This is the code we used in 0.3.0:
sInstance = new SnowPlowManager(context.getApplicationContext());

            Emitter emitter = new Emitter
                    .EmitterBuilder(SNOWPLOW_COLLECTOR_RELEASE, context.getApplicationContext())
                    .method(HttpMethod.GET)
                    .build();

            final Subject subject = new Subject();
            // Screen resolution
            WindowManager wm = (WindowManager) context.getSystemService(Context.WINDOW_SERVICE);
            Display display = wm.getDefaultDisplay();
            Point size = new Point();
            display.getSize(size);
            subject.setScreenResolution(size.x, size.y);

            sAppId = context.getString(R.string.snowplow_app_id);

            tracker = new Tracker
                    .TrackerBuilder(emitter, NAME_SPACE, sAppId)
                    .platform(DevicePlatforms.Mobile)
                    .subject(subject)
                    .build();

**Comment by jbeemster** [comment]
Hi @lixiaoyi so having a new look at your error code it appears to be crashing when adding a `null` value to the request builder: `at android.net.Uri$Builder.appendQueryParameter(Uri.java:1493)`

Now this should not be possible but it could be that 0.3.0 let some values in that it should not.  If possible would you be able to do a debugging run and grab the contents that it attempts to add to the GET request?  Just to make sure that 0.4.0 does not contain the same fault.

You also do not need to include the `snowplow-java-tracker-core` as a dependency anymore.  This was removed in `0.3.0`.

**Comment by lixiaoyi** [comment]
The request is made inside the sdk, we don't know when there is a null value here

I will upgrade to 0.4.0
But there is no code changed from 0.3.0 to 0.4.0 in the implementation of method com.snowplowanalytics.snowplow.tracker.Emitter.requestBuilderGet

I don't understand why it could NullPointerException here.

**Comment by jbeemster** [comment]
While there is no code changes in the requestBuilderGet there have been many updates to the actual payload construction.  The error has to do with what is happening during event building.  A `null` value is finding its way into the payload to be sent.  When the payload is retrieved to be sent on to the collector it is being built into a query string.  It is throwing a `null` pointer trying to build that query.  

As far as I can see there is no fault with RxJava, just with the request builder here.

What is bizarre is that it should be impossible to build a Tracker Payload with a `null` value in it.  Could you potentially also paste in your `tracker.track...` call.  It could be a particular event constructor not behaving itself as well.

**Comment by lixiaoyi** [comment]
Yes I saw the updates of the payload construction.
I will update to 0.4.0 RxJava version, and we will see on next release.
Because we never reproduce it in the beta app. Thank you.

**Comment by jbeemster** [comment]
No worries @lixiaoyi !  Please do let us know if you run into any other problems with the Android Tracker.

As a side note as well, as long as you pass your application context to the Subject it will populate the screen dimensions automatically for you.  So you do not need to do it yourself if you do not want to.

**Comment by jbeemster** [comment]
Closing as non-reproducible...
