### ISSUE TITLE
SQLiteCantOpenDatabaseException: unable to open database file (code 14): , while compiling: PRAGMA journal_mode

### ISSUE THREAD

**Issue by robertoestivill** [snowplow/snowplow-android-tracker#251]
I got several reports on firebase about the following triggered by the Snowplow SDK. 
Any workaround?

Performance
- VM free: 1.25MB
- VM total: 11.41MB
- VM max: 64MB
- Battery level: 15%
- Charging state: Unplugged
- Connection State: Wwan

Device
- Manufacturer: Samsung
- Model: GT-I9300
- Board: Smdk4x12
- Android API: 18
- Android OS: 4.3
- Brand: Samsung
- RAM: 831.05MB
- Orientation: Portrait

```
Caused by android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14): , while compiling: PRAGMA journal_mode
    android.database.sqlite.SQLiteConnection.nativePrepareStatement (SQLiteConnection.java)
    android.database.sqlite.SQLiteConnection.acquirePreparedStatement (SQLiteConnection.java:1118)
    android.database.sqlite.SQLiteConnection.executeForString (SQLiteConnection.java:825)
    android.database.sqlite.SQLiteConnection.setJournalMode (SQLiteConnection.java:511)
    android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration (SQLiteConnection.java:485)
    android.database.sqlite.SQLiteConnection.open (SQLiteConnection.java:384)
    android.database.sqlite.SQLiteConnection.open (SQLiteConnection.java:236)
    android.database.sqlite.SQLiteConnectionPool.openConnectionLocked (SQLiteConnectionPool.java:515)
    android.database.sqlite.SQLiteConnectionPool.open (SQLiteConnectionPool.java:207)
    android.database.sqlite.SQLiteConnectionPool.open (SQLiteConnectionPool.java:178)
    android.database.sqlite.SQLiteDatabase.openInner (SQLiteDatabase.java:891)
    android.database.sqlite.SQLiteDatabase.open (SQLiteDatabase.java:859)
    android.database.sqlite.SQLiteDatabase.openDatabase (SQLiteDatabase.java:696)
    android.app.ContextImpl.openOrCreateDatabase (ContextImpl.java:1234)
    android.content.ContextWrapper.openOrCreateDatabase (ContextWrapper.java:242)
    android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked (SQLiteOpenHelper.java:224)
    android.database.sqlite.SQLiteOpenHelper.getWritableDatabase (SQLiteOpenHelper.java:164)
    com.snowplowanalytics.snowplow.tracker.storage.EventStore.open (EventStore.java:83)
    com.snowplowanalytics.snowplow.tracker.storage.EventStore.<init> (EventStore.java:62)
    com.snowplowanalytics.snowplow.tracker.Emitter.<init> (Emitter.java:232)
    com.snowplowanalytics.snowplow.tracker.Emitter.<init> (Emitter.java:56)
    com.snowplowanalytics.snowplow.tracker.Emitter$EmitterBuilder.build (Emitter.java:210)
```

**Comment by BenFradet** [comment]
Could it be caused by multiple calls to `EventStore.open`?

**Comment by robertoestivill** [comment]
I don't know the internals of the sdk, but I can tell you that's not our case.
The `Emitter` is only initialized and referenced from an `AnalyticsWrapper` class that gets instantiate as a Dagger singleton. So at first sight, there's no chance we are initializing the `Emitter` twice.

**Comment by jbeemster** [comment]
Hey @robertoestivill could you please add the version of the tracker you are using and the code that actually instantiates and sets up the tracker?

**Comment by robertoestivill** [comment]
@jbeemster here it goes:

`com.snowplowanalytics:snowplow-android-tracker:0.6.0@aar`

```
public class TrackerManager {

  private final Subject subject;

  public TrackerManager( @Named("ContextApplication") Context context ) {

    final Emitter emitter = new Emitter.EmitterBuilder("uri", context).build();

    subject = new Subject.SubjectBuilder().context(context).build();

    Tracker.init(new Tracker.TrackerBuilder(emitter, "namespace", "appId", context)
        .level(BuildConfig.DEBUG ? LogLevel.VERBOSE : LogLevel.OFF)
        .subject(subject)
        .platform(DevicePlatforms.Mobile)
        .sessionContext(false)
        .mobileContext(true)
        .geoLocationContext(false)
        .lifecycleEvents(false)
        .applicationCrash(false)
        .build()
    );
  }

  public void trackSomething( ... ){
    Tracker.instance().track( ... )
  }
}
```

Thanks

**Comment by quiro91** [comment]
I'm experiencing the same issue in version 0.6.2, any news about it?

**Comment by alexanderdean** [comment]
Hey @quiro91 could you please add the version of the tracker you are using and the code that actually instantiates and sets up the tracker?

**Comment by quiro91** [comment]
@alexanderdean version 0.6.2, 
```
Emitter emitter = new Emitter.EmitterBuilder(ENDPOINT, getApplicationContext())
                .security(RequestSecurity.HTTPS)
                .build();

Subject subject = new Subject.SubjectBuilder()
                .context(getApplicationContext())
                .build();
subject.setLanguage(interfaceLanguage.toString());

Tracker.init(new Tracker.TrackerBuilder(emitter, getString(R.string.app_name), Platform.getApplicationVersion(getApplicationContext()), getApplicationContext())
                .level(DEBUG)
                .base64(false)
                .subject(subject)
                .sessionContext(true)
                .mobileContext(true)
                .geoLocationContext(false)
                .applicationCrash(true)
                .sessionCheckInterval(10)
                .foregroundTimeout(300)  
                .backgroundTimeout(120)
                .build()
        );
```

**Comment by alexanderdean** [comment]
Thanks @quiro91! We will investigate...

**Comment by ablenesi** [comment]
We are also experiencing the same issue

`com.snowplowanalytics:snowplow-android-tracker:0.6.2@aar`

```
Tracker.TrackerBuilder(
                Emitter.EmitterBuilder(SNOWPLOW_COLLECTOR_URI, context.applicationContext).build(),
                BuildConfig.NAMESPACE,
                BuildConfig.APPLICATION_ID,
                context
            )
                .sessionContext(true)
                .level(if (BuildConfig.DEBUG) LogLevel.VERBOSE else LogLevel.OFF)
                .platform(DevicePlatforms.Mobile)
                .build()
```

**Comment by ablenesi** [comment]
Happened on a OnePlus One, Android 6.0.1 - Only this single user was affected, the crash happened 26 times.

**Comment by mhadam** [comment]
I wonder if this issue is related to external storage or write access privileges.

**Comment by anujmiddha** [comment]
We have the same issue. Our Crashlytics statistics -

Device distribution is across Samsung, Motorola, Lenovo and others.
OS distribution is across versions 5, 6, 7 and 8.
90% of the devices are in background

**Comment by j-oswin** [comment]
We are also experiencing this issue, happening only on Moto e5 play.

![Screen Shot of error in Firebase](https://user-images.githubusercontent.com/3712265/71263734-82417c00-2310-11ea-91d3-bc20745f4bba.png)

**Comment by StayZeal** [comment]
**android 6.0
only one device**
**mylog:**
> E SQLiteLog: (14) cannot open file at line 31320 of [5a3022e081]
E SQLiteLog: (14) os_unix.c:31320: (13) open(/data/user/0/com.*/databases/**.db-journal) -
E SQLiteLog: (14) cannot open file at line 31320 of [5a3022e081]
E SQLiteLog: (14) os_unix.c:31320: (13) open(/data/user/0/com.*/databases/*V3X.db-journal) -
E SQLiteLog: (14) unable to open database file
E SQLiteDatabase: Failed to open database '/data/user/0/com.*/databases/*.db'.
E SQLiteDatabase: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14): , while compiling: PRAGMA journal_mode
E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:896)
E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:641)
E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:323)
E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:297)
E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:218)
E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:196)
E SQLiteDatabase:        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
E SQLiteDatabase:        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
E SQLiteDatabase:        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:836)
E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:821)
E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
E SQLiteDatabase:        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:579)
E SQLiteDatabase:        at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:269)
E SQLiteDatabase:        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
E SQLiteDatabase:        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
...
E SQLiteDatabase:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E SQLiteDatabase:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E SQLiteDatabase:        at java.lang.Thread.run(Thread.java:818)

**os_unix.c:31320: (13)** may  means **EACCES**----__BIONIC_ERRDEF( EACCES         ,  13, "Permission denied" )

but i dont know why.

[related ](https://github.com/greenrobot/greenDAO/issues/319)https://github.com/greenrobot/greenDAO/issues/319

**Comment by matus-tomlein** [comment]
Closing due to inactivity and lack of reports recently.
