### ISSUE TITLE
Exception on v.1.4.1 when API level below 21.

### ISSUE THREAD

**Issue by AlexBenny** [snowplow/snowplow-android-tracker#372]
Hi @AlexBenny, I tried using Snowplow Tracker 1.4.1 and it causes the following error for devices with Android API level below 21:

`java.lang.IllegalStateException: Expected Android API level 21+ but was 19
       at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
       at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
       at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
       at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:202)
       ...`

It seems the dependency OkHttp 3.14.16, which requires Android API level 21+ (https://square.github.io/okhttp/#requirements), is causing this problem.

Can you verify this and, if ever, be reflected in the documentation?

Thank you so much :)

_Originally posted by @jolotan416 in https://github.com/snowplow/snowplow-android-tracker/issues/371#issuecomment-616286917_

**Comment by AlexBenny** [comment]
Thanks @jolotan416 for raising this.
I'll update here for any improvement about the minimum supported version.

**Comment by AlexBenny** [comment]
Fixed along with #373
