### ISSUE TITLE
Getting crash in snowplow in ServiceProvider class

### ISSUE THREAD

**Issue by Prithuld** [snowplow/snowplow-android-tracker#686]
Describe the bug 
**Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
       at java.util.ArrayList.get(ArrayList.java:437)
       at kotlin.collections.CollectionsKt_MutableCollectionsKt.filterInPlace$CollectionsKt_MutableCollectionsKt(MutableCollections.kt:289)
       at kotlin.collections.CollectionsKt__MutableCollectionsKt.removeAll(MutableCollections.kt:274)
       at com.snowplowanalytics.core.tracker.ServiceProvider.removePlugin(ServiceProvider.kt:373)
       at com.snowplowanalytics.core.tracker.PluginsControllerImpl.removePlugin(PluginsControllerImpl.kt:32)
       at com.snowplowanalytics.core.globalcontexts.GlobalContextsControllerImpl.remove(GlobalContextsControllerImpl.kt:51)
       at commonlib.snowplow.DefaultSnowplowAnalyticsTracker.setGlobalUserContext(DefaultSnowplowAnalyticsTracker.kt:106)**
       
**To Reproduce**
Steps to reproduce the behavior or code snippets that produce the issue.

**Expected behavior**

**Screenshots**

**Device informatoin (please complete the following information):**
We are using 6.0.1 library
**Additional context**

**Comment by miike** [comment]
@Prithuld Could you please include information about your usage / configuration to allow us to replicate this issue? (particularly around global contexts)

**Comment by Prithuld** [comment]
As per analysis we see we are calling it from different Dispatchers(IO), but we did not change this part of code very recently
